services:
  - type: web
    name: bloom
    runtime: static
    rootDir: .
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    buildFilter:
      ignoredPaths:
        - src/**/*.test.js
