services:
  - type: web
    name: bloom
    runtime: static
    rootDir: src
    branch: main
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build && ls -R .
    staticPublishPath: ./dist
    buildFilter:
      ignoredPaths:
        - src/**/*.test.js
